README.md
requirements.txt

requirements file

---

testrpc.py

the error was InvalidTransaction: Values way too high
ethereum/transactions.py", line 60, in __init__ | InvalidTransaction: Values way too high!"
and printing out the values showed that self.value was the issue (sample output: 1 3141592 0x0 0)
also fyi, int() doesn't need strip_0x (at least python2.7), but I've kept it for consistency with the rest of the code
```
>>> int('0xff', 16)
255
```

fix value to be int (eg it was being passed to pyethereum as 0x0)

---

setup.py
testrpc/__init__.py
testrpc/__main__.py

When attempting to install the package from `pypi` I was getting this error
```bash
Building wheels for collected packages: eth-testrpc
Running setup.py bdist_wheel for eth-testrpc
Stored in directory: /Users/pipermerriam/Library/Caches/pip/wheels/4a/66/4d/28d73dd7a786188d87e628bf5753a163a5e8863d64460115fb
Successfully built eth-testrpc
Installing collected packages: eth-testrpc
Exception:
Traceback (most recent call last):
File "/Users/pipermerriam/python-environments/eth-phone-number-verification/lib/python3.4/site-packages/pip/basecommand.py", line 223, in main
status = self.run(options, args)
File "/Users/pipermerriam/python-environments/eth-phone-number-verification/lib/python3.4/site-packages/pip/commands/install.py", line 297, in run
root=options.root_path,
File …
```

Make the package installable

---

testrpc/__main__.py

I need to use the `server` object from `testrpc.__main__` from within python codebase.  The current code instantiates the server using command line arguments for `host` and `port` which don't allow the flexibility that I need (ability to run on a different or dynamic port)
I created a new function `create_server` in the `testrpc.__main__` module that handles the server creation.  This allows me to import this function so that I can generate new instances of the server.

Make the rpc server usable outside of the command line

---

testrpc/__main__.py

Ran into an issue where opening multiple async and sync web3 connections caused the server to lock up due to a race condition (stuck receiving on a connection which wasn't currently sending a request while the active client thread was ignored)

use a multithreaded TCP server

---

testrpc/__main__.py

This is an update to #29 
* Calls into the EVM need to be serialized as it is not thread-safe

wrap RPC calls in mutex

---

testrpc/testrpc.py
tests/endpoints/test_eth_getBlockByHash.py
tests/endpoints/test_eth_getBlockByNumber.py

The `getBlockByNumber` and `getBlockByHash` methods were broken.
Fixed them to call the appropriate underlying `ethereum-tester-client` methods.

Fix the two getBlockBy* endpoints

---

README.md
testrpc/server.py
testrpc/testrpc.py
tests/endpoints/test_evm_mine.py

No nice way to advance the blockchain by a single block (mining)
Added an `evm_mine` rpc function that could be used to do this.

add evm_mine rpc method

---

testrpc/testrpc.py

The JSON-RPC spec expects the input value for `web_sha3` to be hex encoded.

fix sha3 to be compliant

---

README.md
conftest.py
requirements.txt
setup.py
testrpc/server.py
testrpc/testrpc.py
tests/endpoints/test_eth_estimateGas.py
tests/endpoints/test_evm_configure.py

The default configuration for `pyethereum` is to have the two fork block numbers set to the values from the main chain.  This isn't normally what people want when they are using it for a test chain.
Pulled in the downstream version of `ethereum-tester-client` which defaults these values to `0` as well as added configuration to the `rpc_configure` endpoint for configuring this.

update deps for homestead block configuration

---

conftest.py
requirements.txt
setup.py
testrpc/__main__.py
testrpc/server.py
tests/endpoints/test_server_accepts_requests.py
tests/server/test_server_running.py

The library was using things that needed to be imported from `gevent` but were not.
* Use gevent threads
* Use gevent sockets
* Use gevent wsgi servers

Fix usage to be compliant with gevent

---

setup.py

There are downstream changes in `ethereum-tester-client` that remove the gevent monkeypatching behavior.
Bumped the dependent version number.

Pull in downstream gevent usage changes

---

testrpc/testrpc.py
tests/filters/test_installing_new_filter.py

The params passed into `newFilter` were being directly fed into the `eth-tester-client` `new_filter` method.
Added some kwargs translation to get the keywords right.

Fix call signature of proxy call to new_filter

---

testrpc/testrpc.py
testrpc/utils.py

Block numbers couldn't be supplied as their hex encoded value (which is the actual RPC spec I think)
Added support for it.

accept hex block numbers

---

testrpc/testrpc.py
testrpc/utils.py

The newly supported hex encoded block numbers borked some things.
Normalize the block numbers for `eth_newFilter` before passing them onwards to `ethereum-tester-client`
Worth noting that this was also fixed upstream via https://github.com/pipermerriam/ethereum-tester-client/pull/25 thansk to @4gn3s.

fix eth_newFilter for hex encoded block numbers

---

README.md
testrpc/rpc.py
tests/endpoints/test_evm_mine.py

`evm_mine` only allowed mining single blocks.  Nice to mine multiple blocks.
Added ability to specify number of blocks to mine

allow specifying number of blocks for evm_mine

---

.travis.yml
README.md
conftest.py
requirements-dev.txt
requirements-gevent.txt
setup.py
testrpc/async/__init__.py
testrpc/async/gevent_async.py
testrpc/async/stdlib_async.py
testrpc/cli.py
testrpc/client/client.py
testrpc/server.py
tests/concurrency/test_ethtester_async.py
tests/endpoints/test_server_accepts_requests.py
tests/server/test_server_running.py
tox.ini

Gevent doesn't play very nicely with others.  It's great if it's used across the whole stack but otherwise it causes problems.  Having it as a hard dependency no longer makes sense.
Added `testrpc.async` module which conditionally imports either stdlib async tools or gevent based ones.

Remove hard gevent dependency

---

requirements-dev.txt
requirements.txt
setup.py

Upstream dependencies were pinned at older versions of `ethereum` and `rlp`.  This has become problematic.
Unpinned to old versions.  Also removed redundant `requirements.txt` file.

update ethereum and pyrlp dependencies

---

setup.py

Library currently doesn't work with latest pyethereum
Pin to `ethereum<2.0.0`

Pin to pyethereum<2.0.0

---

testrpc/client/serializers.py
tests/client/test_get_block_by_number.py

logs_bloom was not the correct length
pad to 256 bytes (`zpad` takes the desired length, not the number of zeros to add)

pad logs_bloom to 256 bytes

---

testrpc/client/serializers.py
tests/client/test_get_block_by_number.py
tests/endpoints/test_eth_getBlockByNumber.py

`logsBloom` was being returned as raw bytes. All other fields are hex-encoded.
hex-encode `logsBloom`

Return logsBloom as hex-encoded

---

testrpc/client/serializers.py
tests/endpoints/test_eth_getBlockByNumber.py

According to the yellow paper, the block nonce should be 8 bytes:
Encoded nonce as 8 bytes instead of 32.

encode nonce as 8 bytes

---

setup.py

see ethereum/web3.py#799
Temporarily pin `rlp` version to  `0.6.0` until the codebase is made compatible with `rlp. 1.0.1`

pin version of rlp

---

testrpc/client/client.py

EVM state was not reverted after a transaction failure in `call()`. This has led to user not able to perform any other transaction after the failed `call()`. In comparison, it should follow the same `try...finally` pattern as the one in `estimate_gas()`.
Wrap `_send_transaction()` with `try...finally` block to ensure `revert_evm()` is called if any exception occurs.

Fix evm state not reverted after a transaction failure in call().
